E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
E
======================================================================
ERROR: test1 (__main__.AvlTest1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "privatetest-c.py", line 14, in test1
    tree = avl.AVL()
AttributeError: module 'avl' has no attribute 'AVL'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
